### PR TITLE
Redirect Career link to linkedin

### PR DESCRIPTION
**Pull request by maknahar**
Redirect Career link to LinkedIn job page of QCI

### CODE REVIEW

**Comment by maknahar** [comment]
Screenshot 2019-10-18 at 7 03 00 PM

@sivachandran Current takes users to this page.

**Comment by maknahar** [comment]
Screenshot 2019-10-18 at 7 07 00 PM

However, this page looks more convenient. The flip side is that URL looks like `https://www.linkedin.com/jobs/search/?f_C=147255&geoId=102713980&keywords=&location=India&locationId=OTHERS.worldwide&originalSubdomain=in` Can we rely on this URL to behave consistently?

**Comment by sivachandran** [comment]
> Can we rely on this URL to behave consistently?
Let's stick the reliable URL.

**Review by sivachandran — APPROVED** [review]

**Comment by maknahar** [comment]
Okay. No change needed on code then @sivachandran

**Pull request merged**
